name: 'Set up the system environment for compilation.'

runs:
  using: 'composite'
  steps:
      - name: Output System OS
        shell: bash
        run: |
          title() {
              echo -e "\033[1;36m"
              echo "╔════════════════════════════════════════════════════════════════════╗"
              echo "║                         $1                         ║"
              echo "╚════════════════════════════════════════════════════════════════════╝"
              echo -e "\033[1;36m"
          }

          footer(){
              echo -e "\033[1;36m"
              echo "╔════════════════════════════════════════════════════════════════════╗"
              echo "║                                                                    ║"
              echo "╚════════════════════════════════════════════════════════════════════╝"
              echo -e "\033[1;36m"
          }

          context() {
              echo -e "\033[0m $1: \033[1;37m$2\033[0m"
          }

          . /etc/os-release

          title "System Information"
          context "OS" "$PRETTY_NAME"
          context "User" "$(whoami)"
          context "Current Folder" "$(pwd)"
          context "Shell" "$SHELL"

          footer

      - name: Check System OS
        shell: bash
        run: |
          . /etc/os-release

          if [ "$ID" = "ubuntu" ]; then
              if [ "$VERSION_ID" = "20.04" ]; then
                  echo "SYSTEM_VERSION=oldest" >> $GITHUB_ENV
              elif [ "$VERSION_ID" = "22.04" ]; then
                  echo "SYSTEM_VERSION=older" >> $GITHUB_ENV
              elif [ "$VERSION_ID" = "24.04" ]; then
                  echo "SYSTEM_VERSION=newer" >> $GITHUB_ENV
              else
                  echo "❌ Not Supported: $VERSION_ID"
                  false
              fi
          elif [ "$ID" = "arch" ]; then
              echo "SYSTEM_VERSION=arch" >> $GITHUB_ENV
          else
              echo "❌ Not Supported: $PRETTY_NAME"
              false
          fi

      - name: Free Disk Space (Ubuntu)
        if: env.FREE_MORE_SPACE == 'true' && env.SYSTEM_VERSION == 'newer' || env.SYSTEM_VERSION == 'older'
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Remove useless tools
        if: env.SYSTEM_VERSION == 'newer' || env.SYSTEM_VERSION == 'older'
        shell: bash
        run: |
          sudo rm -rf /opt/hostedtoolcache
          df -h

      - name: Move Patch and Tools
        shell: bash
        run: |
          # Move patch folder to tmp
          mv $GITHUB_WORKSPACE/Patches /tmp/

          # Set curlx
          mv $GITHUB_WORKSPACE/Bin /tmp/
          chmod 777 /tmp/Bin/curlx.sh
          echo "CURLX=/tmp/Bin/curlx.sh" >> $GITHUB_ENV

          # Copy Shell
          cp /tmp/Bin/found_gcc.sh ./

      - name: Install necessary packages
        shell: bash
        run: |
          if [ "${{ env.SYSTEM_VERSION }}" == "oldest" ]; then
            # Tzdata
            TZ=America/Los_Angeles
            ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
            echo "$TZ" > /etc/timezone

            apt-get update
            apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler wget curl cpio -y
            apt-get install p7zip p7zip-full -y
            apt-get install libtinfo5 -y

            # Install Coccinelle
            if [[ "${{ env.HIDE_STUFF }}" == "true" ]]; then
                apt-get install pkg-config ocaml-nox ocaml-findlib autoconf libpcre3-dev python3-dev menhir libparmap-ocaml-dev libpcre-ocaml-dev -y
                wget https://coccinelle.gitlabpages.inria.fr/website/distrib/coccinelle-1.3.tar.gz
                tar zxf coccinelle-1.3.tar.gz
                cd coccinelle-1.3
                ./autogen
                ./configure
                make
                make install
            fi

            if [ "${{ env.PYTHON_VERSION }}" == "3" ]; then
                apt install python3 -y
                rm -rf /usr/bin/python
                ln -s /usr/bin/python3 /usr/bin/python
                echo ">>>>>>><<<<<<<"
                echo ">            <"
                echo "> Python - 3 <"
                echo ">            <"
                echo ">>>>>>><<<<<<<"
            elif [ "${{ env.PYTHON_VERSION }}" == "2" ]; then
                apt install python2 -y
                rm -rf /usr/bin/python
                ln -s /usr/bin/python2.7 /usr/bin/python
                echo ">>>>>>><<<<<<<"
                echo ">            <"
                echo "> Python - 2 <"
                echo ">            <"
                echo ">>>>>>><<<<<<<"
            else
                echo ">>>>>>>>>>>>>>>>>Error<<<<<<<<<<<<<<<<<"
                echo ">                                     <"
                echo ">You need choose a vaild python version"
                echo ">                                     <"
                echo ">>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<"
                false
            fi

            echo "Python Version"
            echo ">$(python -V)"
            echo ">>EOF"

          elif [ "${{ env.SYSTEM_VERSION }}" == "older" ]; then

            sudo apt-get update
            sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler wget curl cpio -y
            sudo apt-get install p7zip p7zip-full -y
            sudo apt-get install libtinfo5 -y

            # Install Coccinelle
            if [[ "${{ env.HIDE_STUFF }}" == "true" ]]; then
                apt-get install pkg-config ocaml-nox ocaml-findlib autoconf libpcre3-dev python3-dev menhir libparmap-ocaml-dev libpcre-ocaml-dev -y
                wget https://coccinelle.gitlabpages.inria.fr/website/distrib/coccinelle-1.3.tar.gz
                tar zxf coccinelle-1.3.tar.gz
                cd coccinelle-1.3
                ./autogen
                ./configure
                make
                make install
            fi

            if [ "${{ env.PYTHON_VERSION }}" == "3" ]; then
                sudo apt install python3 -y
                sudo rm -rf /usr/bin/python
                sudo ln -s /usr/bin/python3 /usr/bin/python
                echo ">>>>>>><<<<<<<"
                echo ">            <"
                echo "> Python - 3 <"
                echo ">            <"
                echo ">>>>>>><<<<<<<"
            elif [ "${{ env.PYTHON_VERSION }}" == "2" ]; then
                sudo apt install python2 -y
                sudo rm -rf /usr/bin/python
                sudo ln -s /usr/bin/python2.7 /usr/bin/python
                echo ">>>>>>><<<<<<<"
                echo ">            <"
                echo "> Python - 2 <"
                echo ">            <"
                echo ">>>>>>><<<<<<<"
            else
                echo ">>>>>>>>>>>>>>>>>Error<<<<<<<<<<<<<<<<<"
                echo ">                                     <"
                echo ">You need choose a vaild python version"
                echo ">                                     <"
                echo ">>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<"
                false
            fi

            echo "Python Version"
            echo ">"
            echo "$(python -V)"
            echo ">"
            echo ">EOF"

          elif [ "${{ env.SYSTEM_VERSION }}" == "newer" ]; then

            sudo apt update
            sudo apt install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler cpio coccinelle -y
            sudo apt-get install zstd libc6 binutils libc6-dev-i386 gcc g++ p7zip p7zip-full -y

            # Install Libtinfo5
            ${{ env.CURLX }} http://launchpadlibrarian.net/580830584/libtinfo5_6.3-2_amd64.deb libtinfo5.deb
            sudo apt install ./libtinfo5.deb
            rm -f libtinfo5.deb

            if [ "${{ env.PYTHON_VERSION }}" == "3" ]; then
                sudo apt install python3 -y
                sudo rm -rf /usr/bin/python
                sudo ln -s /usr/bin/python3 /usr/bin/python
                echo ">>>>>>><<<<<<<"
                echo ">            <"
                echo "> Python - 3 <"
                echo ">            <"
                echo ">>>>>>><<<<<<<"
            elif [ "${{ env.PYTHON_VERSION }}" == "2" ]; then
                wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
                tar -xvf Python-2.7.18.tgz
                cd Python-2.7.18
                ./configure
                make -j$(nproc)
                sudo make install
                curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
                sudo python2.7 get-pip.py
                sudo update-alternatives --install /usr/bin/python python /usr/local/lib/python2.7 1
                cd ../
                rm -rf Python-2.7.18 Python-2.7.18.tgz
                echo ">>>>>>><<<<<<<"
                echo ">            <"
                echo "> Python - 2 <"
                echo ">            <"
                echo ">>>>>>><<<<<<<"
            else
                echo ">>>>>>>>>>>>>>>>>Error<<<<<<<<<<<<<<<<<"
                echo ">                                     <"
                echo ">You need choose a vaild python version"
                echo ">                                     <"
                echo ">>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<"
                false
            fi

            echo "Python Version"
            echo ">"
            echo "$(python -V)"
            echo ">"
            echo ">EOF"

          elif [ "${{ env.SYSTEM_VERSION }}" == "arch" ]; then

            pacman-key --init
            pacman -Syyu --noconfirm
            pacman -S git base-devel systemd wget rustup curl patch ccache automake flex lzop bison gperf zip curl bzip2 squashfs-tools pngcrush schedtool make optipng maven pwgen minicom bc unzip 7zip zstd binutils gcc wget which libxml2-legacy cpio --noconfirm

            # Install Coccinelle
            if [[ "${{ env.HIDE_STUFF }}" == "true" ]]; then
                echo -e "\n[archlinuxcn]\nServer = https://repo.archlinuxcn.org/\$arch" >> /etc/pacman.conf
                pacman -Syy
                pacman -S archlinuxcn-keyring --noconfirm
                pacman -S coccinelle --noconfirm
            fi

            if [ "${{ env.PYTHON_VERSION }}" == "3" ]; then
                pacman -S python3 --noconfirm
                rm -rf /usr/bin/python
                ln -s /usr/bin/python3 /usr/bin/python
                echo ">>>>>>><<<<<<<"
                echo ">            <"
                echo "> Python - 3 <"
                echo ">            <"
                echo ">>>>>>><<<<<<<"
            elif [ "${{ env.PYTHON_VERSION }}" == "2" ]; then
                echo ">>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<"
                echo ">                              <"
                echo "> Could not supported Python 2 <"
                echo ">                              <"
                echo ">>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<"
                false
            else
                echo ">>>>>>>>>>>>>>>>>Error<<<<<<<<<<<<<<<<<"
                echo ">                                     <"
                echo ">You need choose a vaild python version"
                echo ">                                     <"
                echo ">>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<"
                false
            fi

            echo "Python Version"
            echo ">"
            echo "$(python -V)"
            echo ">"
            echo ">EOF"

            # Update Rust Toolchain
            rustup default stable

          else
            echo "❌ Your system os cannot supported."
          fi

      - name: Install GNU GCC
        if: env.GCC_GNU == 'true'
        shell: bash
        run: |
          if [ "${{ env.SYSTEM_VERSION }}" == "newer" ] || [ "${{ env.SYSTEM_VERSION }}" == "older" ] || [ "${{ env.SYSTEM_VERSION }}" == "oldest" ]; then

            sudo apt install binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
            sudo apt install gcc-arm-linux-gnueabi -y

            echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
            echo "GCC_32=CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV

          elif [ "${{ env.SYSTEM_VERSION }}" == "arch" }} ]; then

            pacman -S aarch64-linux-gnu-binutils aarch64-linux-gnu-gcc aarch64-linux-gnu-glibc aarch64-linux-gnu-linux-api-headers aarch64-linux-gnu-glibc --noconfirm
            pacman -S arm-none-eabi-binutils arm-none-eabi-gcc arm-none-eabi-newlib --noconfirm

            echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
            echo "GCC_32=CROSS_COMPILE_ARM32=arm-none-eabi-" >> $GITHUB_ENV

          else
            echo "❌ Your system os cannot supported."
          fi

      - name: Set Compile Environment
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE

          # Set GCC
          if [[ "${{ env.CLANG_SOURCE }}" == *proton* ]]; then
            echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
            echo ">                            <"
            echo ">   Detected Pronton Clang   <"
            echo ">     Needn't other GCC      <"
            echo ">                            <"
            echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
            echo "GCC_64=CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
            echo "GCC_32=CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV

          elif [[ "${{ env.GCC_GNU }}" == "true" ]]; then
            echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
            echo ">                            <"
            echo ">      Detected GNU GCC      <"
            echo ">                            <"
            echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
          elif [[ -z "${{ env.GCC_64_SOURCE }}" ]] && [[ -z "${{ env.GCC_32_SOURCE }}" ]]; then
            echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
            echo ">                            <"
            echo ">   Have not found any GCC   <"
            echo ">                            <"
            echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
          elif [[ -n "${{ env.GCC_64_SOURCE }}" ]] && [[ -n "${{ env.GCC_32_SOURCE }}" ]]; then
            echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
            echo ">                            <"
            echo ">         Get GCC 64         <"
            echo ">                            <"
            echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
            if [[ "${{ env.GCC_64_SOURCE }}" == *".git" ]]; then
              git clone "${{ env.GCC_64_SOURCE }}" -b "${{ env.GCC_64_BRANCH }}" gcc-64 --depth=1
            elif [[ "${{ env.GCC_64_SOURCE }}" == *'.tar.gz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_64_SOURCE }}" gcc-64.tar.gz
              mkdir gcc-64
              tar -C gcc-64/ -zxf gcc-64.tar.gz
            elif [[ "${{ env.GCC_64_SOURCE }}" == *'.tar.xz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_64_SOURCE }}" gcc-64.tar.xz
              mkdir gcc-64
              tar -C gcc-64/ -xf gcc-64.tar.xz --strip-components 1
            elif [[ "${{ env.GCC_64_SOURCE }}" == *'.xz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_64_SOURCE }}" gcc-64.xz
              mkdir gcc-64
              tar -C gcc-64/ -xf gcc-64.xz --strip-components 1
            elif [[ "${{ env.GCC_64_SOURCE }}" == *'.zip' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_64_SOURCE }}" gcc-64.zip
              mkdir gcc-64
              unzip gcc-64.zip -d gcc-64/
            else
                echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
                echo ">                            <"
                echo ">Please input vaild GCC link!<"
                echo ">                            <"
                echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
                false
            fi
            bash found_gcc.sh GCC_64

            echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
            echo ">                            <"
            echo ">         Get GCC 32         <"
            echo ">                            <"
            echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
            if [[ "${{ env.GCC_32_SOURCE }}" == *".git" ]]; then
              git clone "${{ env.GCC_32_SOURCE }}" -b "${{ env.GCC_32_BRANCH }}" gcc-32 --depth=1
            elif [[ "${{ env.GCC_32_SOURCE }}" == *'.tar.gz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_32_SOURCE }}" gcc-32.tar.gz
              mkdir gcc-32
              tar -C gcc-32/ -zxf gcc-32.tar.gz
            elif [[ "${{ env.GCC_32_SOURCE }}" == *'.tar.xz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_32_SOURCE }}" gcc-32.tar.xz
              mkdir gcc-32
              tar -C gcc-32/ -xf gcc-32.tar.xz --strip-components 1
            elif [[ "${{ env.GCC_32_SOURCE }}" == *'.xz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_32_SOURCE }}" gcc-32.xz
              mkdir gcc-32
              tar -C gcc-32/ -xf gcc-32.xz --strip-components 1
            elif [[ "${{ env.GCC_32_SOURCE }}" == *'.zip' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_32_SOURCE }}" gcc-32.zip
              mkdir gcc-32
              unzip gcc-32.zip -d gcc-32/
            else
                echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
                echo ">                            <"
                echo ">Please input vaild GCC link!<"
                echo ">                            <"
                echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
                false
            fi
            bash found_gcc.sh GCC_32

          elif [[ -n "${{ env.GCC_32_SOURCE }}" ]]; then
            echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
            echo ">                            <"
            echo ">         Get GCC 32         <"
            echo ">                            <"
            echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
            if [[ "${{ env.GCC_32_SOURCE }}" == *".git" ]]; then
              git clone "${{ env.GCC_32_SOURCE }}" -b "${{ env.GCC_32_BRANCH }}" gcc-32 --depth=1
            elif [[ "${{ env.GCC_32_SOURCE }}" == *'.tar.gz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_32_SOURCE }}" gcc-32.tar.gz
              mkdir gcc-32
              tar -C gcc-32/ -zxf gcc-32.tar.gz
            elif [[ "${{ env.GCC_32_SOURCE }}" == *'.tar.xz' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_32_SOURCE }}" gcc-32.tar.xz
              mkdir gcc-32
              tar -C gcc-32/ -xf gcc-32.tar.xz --strip-components 1
            elif [[ "${{ env.GCC_32_SOURCE }}" == *'.zip' ]]; then
              ${{ env.CURLX }} "${{ env.GCC_32_SOURCE }}" gcc-32.zip
              mkdir gcc-32
              unzip gcc-32.zip -d gcc-32/
            else
                echo ">>>>>>>>>>GCC Status<<<<<<<<<<"
                echo ">                            <"
                echo ">Please input vaild GCC link!<"
                echo ">                            <"
                echo ">>>>>>>>>>>>>>><<<<<<<<<<<<<<<"
                false
            fi
            bash found_gcc.sh GCC_32_ONLY
          fi

          # Set Clang
          if [[ -z "${{ env.CLANG_SOURCE }}" ]]; then
            echo ">>>>>>>>>>Clang Status<<<<<<<<<<"
            echo ">                              <"
            echo ">        Not Set Clang!        <"
            echo ">                              <"
            echo ">>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<"
          else
            echo ">>>>>>>>>>Clang Status<<<<<<<<<<"
            echo ">                              <"
            echo ">          Get Clang.          <"
            echo ">                              <"
            echo ">>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<"

            if [[ "${{ env.CLANG_SOURCE }}" == *".git" ]]; then
                git clone "${{ env.CLANG_SOURCE }}" -b "${{ env.CLANG_BRANCH }}" clang-custom --depth=1
            elif [[ "${{ env.CLANG_SOURCE }}" == *'.tar.gz' ]]; then
                ${{ env.CURLX }} "${{ env.CLANG_SOURCE }}" clang.tar.gz
                mkdir clang-custom
                tar -C clang-custom/ -zxf clang.tar.gz
            elif [[ "${{ env.CLANG_SOURCE }}" == *'.tar.xz' ]]; then
                ${{ env.CURLX }} "${{ env.CLANG_SOURCE }}" clang.tar.xz
                mkdir clang-custom
                tar -C clang-custom/ -xf clang.tar.xz --strip-components 1
            elif [[ "${{ env.CLANG_SOURCE }}" == *'.zip' ]]; then
                ${{ env.CURLX }} "${{ env.CLANG_SOURCE }}" clang.zip
                mkdir clang-custom
                unzip clang.zip -d clang-custom/
            elif [[ "${{ env.CLANG_SOURCE }}" == *"antman" ]]; then
                mkdir clang-custom
                cd clang-custom
                ${{ env.CURLX }} "${{ env.CLANG_SOURCE }}" antman
                chmod +x antman
                bash antman -S
            elif [[ "${{ env.CLANG_SOURCE }}" == *"android.googlesource.com"* ]]; then
                git clone "${{ env.CLANG_SOURCE }}" -b "${{ env.CLANG_BRANCH }}" clang-custom --depth=1
                SUBDIR=$(find clang-custom -maxdepth 1 -type d -name 'clang-r*' | head -n 1)
                if [ -n "$SUBDIR" ]; then
                 mv "$SUBDIR"/* clang-custom/
                fi    
            else
                echo ">>>>>>>>>>Clang Status<<<<<<<<<<"
                echo ">                              <"
                echo ">Please input vaild Clang link!<"
                echo ">                              <"
                echo ">>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<"
                false
            fi
          fi
