name: 'Pack Process.'

runs:
  using: 'composite'
  steps:
      - name: Make Anykernel3 Flasher
        if: env.PACK_METHOD == 'Anykernel3'
        shell: bash
        run: |
          TIME=$(date +"%Y%m%d%H%M%S")

          # 🔥 修复：不进 device_kernel，直接在当前目录！
          cd $GITHUB_WORKSPACE

          # 🔥 修复：路径直接用当前 out
          IMAGE_DIR="$GITHUB_WORKSPACE/out/arch/arm64/boot"

          mkdir -p tmp

          if [[ "${{ env.AK3_SOURCE }}" =~ "osm0sis" ]]; then
            sed -i 's/ExampleKernel by osm0sis @ xda-developers/NonGKI Kernel Build by JackAltman @ Github/g' Anykernel3/anykernel.sh
            sed -i 's/do.devicecheck=1/do.devicecheck=0/g' Anykernel3/anykernel.sh
            sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' Anykernel3/anykernel.sh
            sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' Anykernel3/anykernel.sh
            echo "Now using official Anykernel3."
          else
            echo "Now using custom Anykernel3."
          fi

          # 优先使用修补好的 oImage
          if [[ -f "$GITHUB_WORKSPACE/oImage" ]]; then
            cp -fp "$GITHUB_WORKSPACE/oImage" tmp/Image
            echo "✅ 使用已修补内核 oImage"
          elif [[ -f "$IMAGE_DIR/Image.gz-dtb" ]]; then
            cp -fp $IMAGE_DIR/Image.gz-dtb tmp
            echo "Found Image.gz-dtb !"
          elif [[ -f "$IMAGE_DIR/Image.gz" ]]; then
            cp -fp $IMAGE_DIR/Image.gz tmp
            echo "Found Image.gz !"
          elif [[ -f "$IMAGE_DIR/Image" ]]; then
            cp -fp $IMAGE_DIR/Image tmp
            echo "Found Image !"
          fi

          if [[ -f "$IMAGE_DIR/dtbo.img" ]]; then
            cp -fp $IMAGE_DIR/dtbo.img tmp
            echo "Found dtbo.img !"
          fi

          if [[ -f "$IMAGE_DIR/dtb" ]]; then
            cp -fp $IMAGE_DIR/dtb tmp
            echo "Found DTB!"
          fi

          if [ "${{ env.PACK_KMODULES }}" == "true" ]; then
            mkdir -p tmp/modules/vendor/lib/modules
            find $GITHUB_WORKSPACE/out/ -name "*.ko" -exec cp -fp {} tmp/modules/vendor/lib/modules/ \;
          fi

          cp -rp ./Anykernel3/* tmp
          cd tmp
          7za a -mx9 tmp.zip *
          cd ..
          cp -fp tmp/tmp.zip ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}.zip
          rm -rf tmp

          echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}.zip" >> $GITHUB_ENV
