name: 'Preparation for the official start of the compilation steps.'

runs:
  using: 'composite'
  steps:
      - name: Get Kernel
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          git clone --recursive "${{ env.KERNEL_SOURCE }}" -b "${{ env.KERNEL_BRANCH }}" device_kernel --depth=1

          if [[ -f "device_kernel/.gitmodules" ]]; then
            cd device_kernel
            git submodule init
            git submodule update
            cd ../
            echo "[+] Detected GitModules."

          fi

          # Get Kernel Version

          KERNEL_VERSION=$(head -n 3 $GITHUB_WORKSPACE/device_kernel/Makefile | grep -E 'VERSION|PATCHLEVEL' | awk '{print $3}' | paste -sd '.')
          echo "KERNEL_VERSION=$(head -n 3 device_kernel/Makefile | grep -E 'VERSION|PATCHLEVEL' | awk '{print $3}' | paste -sd '.')" >> $GITHUB_ENV
          echo "FIRST_VERSION=$(echo "$KERNEL_VERSION" | awk -F '.' '{print $1}')" >> $GITHUB_ENV
          echo "SECOND_VERSION=$(echo "$KERNEL_VERSION" | awk -F '.' '{print $2}')" >> $GITHUB_ENV

      - name: Get Kernel Arch
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          if [[ -d "arch/arm64/configs" ]]; then
            echo "KERNEL_ARCH=arm64" >> $GITHUB_ENV
          else
            echo "[-] Non-ARM64 Devies not supported!"
            false
          fi

      - name: Get Packing Tools
        shell: bash
        run: |
          # Set ${{ env.PACK_METHOD }}

          if [[ "${{ env.PACK_METHOD }}" == "Anykernel3" ]]; then
            cd $GITHUB_WORKSPACE/device_kernel
            if [[ -d "Anykernel3" ]]; then
              echo "Found Anykernel3 in Kernel!"
            else
              git clone "${{ env.AK3_SOURCE }}" -b "${{ env.AK3_BRANCH }}" Anykernel3 --depth=1
            fi
          elif [[ "${{ env.PACK_METHOD }}" == "MKBOOTIMG" ]] || [ "${{ env.DEFCONFIG_FROM_BOOT }}" == "true" ]; then
            cd $GITHUB_WORKSPACE
            git clone https://android.googlesource.com/platform/system/tools/mkbootimg $GITHUB_WORKSPACE/mkboottools -b main-kernel-build-2024 --depth=1
            ${{ env.CURLX }} ${{ env.BOOT_SOURCE }} $GITHUB_WORKSPACE/boot_source_${{ env.DEVICE_NAME }}.img
            cd device_kernel
          else
            echo "Need packing method! "
            false
          fi
          echo "PACK_METHOD=${{ env.PACK_METHOD }}" >> $GITHUB_ENV

      - name: Get DEFCONFIG
        if: env.DEFCONFIG_SOURCE != '' || env.DEFCONFIG_FROM_BOOT == 'true'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          if [[ -n "${{ env.DEFCONFIG_SOURCE }}" ]]; then
            ${{ env.CURLX }} ${{ env.DEFCONFIG_SOURCE }} device_kernel/arch/"${{ env.KERNEL_ARCH }}"/configs/${{ env.DEFCONFIG_NAME }}

          elif [[ -z "${{ env.DEFCONFIG_ORIGIN_IMAGE }}" ]]; then
            if [[ "${{ env.DEFCONFIG_FROM_BOOT }}" == "true" ]]; then
                if [[ -f "${{ env.BOOT_SOURCE }}" ]]; then
                    ${{ env.CURLX }} "${{ env.BOOT_SOURCE }}" $GITHUB_WORKSPACE/boot.img
                    $GITHUB_WORKSPACE/mkboottools/unpack_bootimg.py --boot_img $GITHUB_WORKSPACE/boot.img
                    mv $GITHUB_WORKSPACE/out/kernel $GITHUB_WORKSPACE/device_kernel/Image
                    $GITHUB_WORKSPACE/device_kernel/scripts/extract-ikconfig $GITHUB_WORKSPACE/device_kernel/Image > $GITHUB_WORKSPACE/device_kernel/arch/"${{ env.KERNEL_ARCH }}"/configs/${{ env.DEFCONFIG_NAME }}

                fi
            else
                ${{ env.CURLX }} "${{ env.DEFCONFIG_ORIGIN_IMAGE }}" $GITHUB_WORKSPACE/device_kernel/Image
                $GITHUB_WORKSPACE/device_kernel/scripts/extract-ikconfig $GITHUB_WORKSPACE/device_kernel/Image > $GITHUB_WORKSPACE/device_kernel/arch/"${{ env.KERNEL_ARCH }}"/configs/${{ env.DEFCONFIG_NAME }}

            fi
          fi

      - name: Cleaned KernelSU and Hook
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          cp /tmp/Bin/clean_hook.sh ./
          bash clean_hook.sh

      - name: Set KernelSU
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          # Function
          KERNELSU_AUTO(){
            if [[ "${{ env.KERNELSU_AUTO_FORK }}" == "xxksu" ]]; then
                KERNELSU_AUTHOR="backslashxx"
                KERNELSU_NAME="KernelSU"
                KERNELSU_ORIGIN_BRANCH="master"
                if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
                    echo "${{ env.KERNELSU_AUTO_FORK }} doesn't support SuSFS! "
                    false
                else
                    KERNELSU_BRANCH="master"
                fi
            elif [[ "${{ env.KERNELSU_AUTO_FORK }}" == "rsuntk" ]]; then
                KERNELSU_AUTHOR="rsuntk"
                KERNELSU_NAME="KernelSU"
                KERNELSU_ORIGIN_BRANCH="main"
                if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
                    echo "${{ env.KERNELSU_AUTO_FORK }} doesn't support SuSFS! "
                    false
                else
                    KERNELSU_BRANCH="main"
                fi
            elif [[ "${{ env.KERNELSU_AUTO_FORK }}" == "sukisu" ]]; then
                KERNELSU_AUTHOR="SukiSU-Ultra"
                KERNELSU_NAME="SukiSU-Ultra"
                KERNELSU_ORIGIN_BRANCH="main"
                if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
                    KERNELSU_BRANCH="builtin"
                else
                    KERNELSU_BRANCH="builtin"
                fi
            elif [[ "${{ env.KERNELSU_AUTO_FORK }}" == "next" ]]; then
                KERNELSU_AUTHOR="KernelSU-Next"
                KERNELSU_NAME="KernelSU-Next"
                KERNELSU_ORIGIN_BRANCH="legacy"
                if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
                    echo "${{ env.KERNELSU_AUTO_FORK }} doesn't support SuSFS! "
                    false
                else
                    KERNELSU_BRANCH="legacy"
                fi
            elif [[ "${{ env.KERNELSU_AUTO_FORK }}" == "resukisu" ]]; then
                KERNELSU_AUTHOR="ReSukiSU"
                KERNELSU_NAME="ReSukiSU"
                KERNELSU_ORIGIN_BRANCH="main"
                if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
                    KERNELSU_BRANCH="main"
                else
                    KERNELSU_BRANCH="main"
                fi
            else
                echo "Please input vaild fork name!"
                false
            fi

            if [[ "${{ env.KERNELSU_AUTO_FORK }}" == "next" ]]; then
                KERNELSU_FOLDER="KernelSU-Next"
                echo "KERNELSU_NAME=$KERNELSU_FOLDER" >> $GITHUB_ENV

            else
                KERNELSU_FOLDER="KernelSU"
                echo "KERNELSU_NAME=$KERNELSU_FOLDER" >> $GITHUB_ENV

            fi

            if [[ "${{ env.KERNELSU_METHOD }}" == "shell" ]]; then
                curl -sSL "https://raw.githubusercontent.com/${KERNELSU_AUTHO
