        - name: Upload Build Artifacts For Anykernel3
          if: env.PACK_METHOD == 'Anykernel3'
          uses: actions/upload-artifact@v7
          with:
               -name: ${{ env.PACK_NAME }}
               # 1. 引号包裹，规避括号特殊字符解析bug
               # 2. 用 ${{ github.workspace }} 锁定绝对工作目录
               path: "${{ github.workspace }}/${{ env.PACK_NAME }}"
               jobs:
                 overwrite: true

        - name: Upload Build Artifacts For Boot Image
          if: env.PACK_METHOD == 'MKBOOTIMG'
          uses: actions/upload-artifact@v7
          with:
          name: Kernel-${{ env.PACK_NAME }}
          path: ${{ env.PACK_NAME }}
          overwrite: true
