name: 'Patch Kernel for no-kprobe.'

runs:
  using: 'composite'
  steps:
      - name: Patch Kernel for no-kprobe
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          # Detect SuSFS is used to enable the SuSFS inline hook
          if [[ ${{ env.SUSFS_ENABLE }} == "true" ]]; then
            # Core
            cp /tmp/Patches/susfs_inline_hook_patches.sh ./
            bash susfs_inline_hook_patches.sh ./

            echo "[+] executed SuSFS inline hook successfully."

            if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" != "true" ]]; then
                cp /tmp/Patches/backport_selinux_patches.sh ./

                bash backport_selinux_patches.sh
                echo "[+] Patched SELinux."
            else
                echo "[-] Skipped SELinux Patch."
            fi

          # Check syscall hook
          elif [[ ${{ env.HOOK_METHOD }} == "syscall" ]]; then
            # Core
            cp /tmp/Patches/syscall_hook_patches.sh ./
            bash syscall_hook_patches.sh ./

            echo "[+] executed syscall hook successfully."

            if [[ "${{ env.BASEBAND_GUARD_ENABLE }}" != "true" ]]; then
                cp /tmp/Patches/backport_selinux_patches.sh ./

                bash backport_selinux_patches.sh
                echo "[+] Patched SELinux."
            else
                echo "[-] Skipped SELinux Patch."
            fi

          else
            echo "[-] please input a vaild option!"
            false

          fi
