name: Build msm_drm.ko
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install full toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libelf-dev libssl-dev dwarves git \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Clone kernel
        run: |
          git clone --depth=1 -b hyper-14 https://github.com/zttlove/android_kernel_xiaomi_sm8350-miui.git kernel

      - name: Fix KernelSU
        run: |
          cd kernel
          sed -i 's/^source "drivers\/kernelsu\/Kconfig"/# &/' drivers/Kconfig
          sed -i 's/^obj-\$(CONFIG_KERNELSU) += kernelsu\//# &/' drivers/Makefile

      - name: Set env
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV

      - name: Build
        run: |
          cd kernel
          make vendor/star_defconfig
          make -j$(nproc)
          make -j$(nproc) M=drivers/gpu/drm/msm modules

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: msm_drm_sm8350
          path: kernel/drivers/gpu/drm/msm/msm_drm.ko
          if-no-files-found: error
