name: Clean Broken Action
on:
  workflow_dispatch

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove pack-process
        run: |
          rm -rf .github/workflows/pack-process
          git config user.name "Clean Bot"
          git config user.email "clean@localhost"
          git add .
          git commit -m "Remove broken pack-process action"
          git push
